"""empty message

Revision ID: 275cc3aa6611
Revises: f664d62ab8f8
Create Date: 2018-07-10 21:56:46.038093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275cc3aa6611'
down_revision = 'f664d62ab8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
